[package]
name = "aow"
description = "A command line tool for adb to connect devices over wifi"
version = "0.1.0"
authors = ["Kaustubh Patange <developerkp16@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"

[package.metadata.deb]
extended-description = """\
Adb Over Wifi (aow) is a command line tool for adb to connect devices over wifi. \
"""
depends = "$auto"
section = "utility"
priority = "optional"

[dependencies]
regex = "1"
wait-timeout = "0.2.0"