name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        run: cargo build --release
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c -7)"
      - name: Sending complete notifications
        if: (!startsWith(github.event.pusher, '')) && startsWith(github.event.pusher.name, 'KaustubhPatange')
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
        args: "${{ github.event.repository.full_name }} with commit ${{ steps.vars.outputs.sha_short }} had a successful build!"
      - name: Sending complete PR notifications
        if: (!startsWith(github.event.pull_request, ''))
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "A new pull request is made by ${{ github.event.pull_request.user.login }} at ${{ github.event.pull_request.html_url }}"
